### ISSUE TITLE
bootstrap site

### ISSUE THREAD

**Issue by michaelkuty** [django-leonardo/django-leonardo#69]
now we have simple PoC for easy scaffolding new page
https://github.com/django-leonardo/django-leonardo/blob/master/leonardo/module/web/utils/bootstrap_example.py#L5

add support for loading from yaml, json etc and rewrite first step in create new page
will be choose of bootstrap template from loaded files which may lives in the
conf.d/.. or something like this

```
  auth.User:
    admin:
      password: root
      mail: root@admin.cz
  web.Page:
    QuickStart:
      title: Quickstart
      slug: quickstart
      override_url: /
      featured: false
      theme: __first__
      in_navigation: true
      active: true
      color_scheme: __first__
      content:
        header:
          web.SiteHeadingWidget:
            attrs:
              site_title: Leonardo Site
              content_theme: navbar
              base_theme: default
            dimenssions:
              md: 2

        web.TreeNavigationWidget:
          attrs:
            depth: 2,
            content_theme: navbar
            base_theme: default
          dimenssions:
            md: 6
        web.UserLoginWidget:
          attrs:
            inline: true
            type: 2
            content_theme: navbar
            base_theme: default
              dimenssions:
                md: 4
```
